# Generated by Django 4.1.7 on 2023-04-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=255)),
                ('news_title', models.CharField(max_length=255)),
                ('news_url', models.CharField(max_length=255)),
                ('news_registered_date', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CardanoADA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=255)),
                ('news_title', models.CharField(max_length=255)),
                ('news_url', models.CharField(max_length=255)),
                ('news_registered_date', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ethereum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=255)),
                ('news_title', models.CharField(max_length=255)),
                ('news_url', models.CharField(max_length=255)),
                ('news_registered_date', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EthereumClassic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=255)),
                ('news_title', models.CharField(max_length=255)),
                ('news_url', models.CharField(max_length=255)),
                ('news_registered_date', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='XRP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=255)),
                ('news_title', models.CharField(max_length=255)),
                ('news_url', models.CharField(max_length=255)),
                ('news_registered_date', models.CharField(max_length=255)),
            ],
        ),
    ]
